# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.1.2
_src_path: https://github.com/napari/napari-plugin-template
display_name: Spam
email: jules.vanaret@epfl.ch
full_name: Jules Vanaret
github_repository_url: provide later
github_username_or_organization: jules-vanaret
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: false
install_dependabot: false
install_precommit: false
license: GNU GPL v3.0
module_name: napari_spam
plugin_name: napari-spam
short_description: A simple plugin to load results from Spam in Napari
